apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store-operator
  template:
    metadata:
      labels:
        app: thanos-store-operator
    spec:
      serviceAccountName: thanos-store-operator
      containers:
      - name: operator
        image: harbor.local:32295/thanos-store-operator:v1.0.0
        imagePullPolicy: IfNotPresent
#        args: ["--config", "/app/config/config.yaml"]
        volumeMounts:
        - name: config
          mountPath: /app/config
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
          requests:
            memory: "32Mi"
            cpu: "100m"
      volumes:
      - name: config
        configMap:
          name: thanos-operator-config
